name: ximp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0
      - scipy==1.16.0
      - rdkit==2024.9.5
      - rdkit-stubs==0.8
      - tqdm==4.67.1
      - matplotlib==3.10.0
      - pandas==2.2.3
      - seaborn==0.13.2
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - jupyter
      - --find-links https://data.pyg.org/whl/torch-2.6.0+cu124.html
      - torch-geometric==2.6.1
      - torch-scatter
      - torch-sparse
